jhipsterspringboot-elasticsearch:
  container_name: jhipsterspringboot-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/jhipsterspringboot/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
jhipsterspringboot-postgresql:
  container_name: jhipsterspringboot-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/jhipsterspringboot/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=jhipsterspringboot
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
